"""empty message

Revision ID: 1705234a0d0a
Revises: 
Create Date: 2020-07-25 15:20:25.051969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1705234a0d0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staffUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('studentUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('teacherUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('breathecodeID', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('cohort', sa.String(length=80), nullable=False),
    sa.Column('rut', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['studentUsers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecodeID'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('enrrollment_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('breathecodeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breathecodeID'], ['profiles.breathecodeID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecodeID')
    )
    op.create_table('financing_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('months', sa.String(length=100), nullable=False),
    sa.Column('monthlyFee', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('job_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breathecodeID', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['breathecodeID'], ['profiles.breathecodeID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecodeID')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=200), nullable=False),
    sa.Column('bank', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('job_profiles')
    op.drop_table('invoices')
    op.drop_table('financing_agreements')
    op.drop_table('enrrollment_agreements')
    op.drop_table('credit_notes')
    op.drop_table('profiles')
    op.drop_table('teacherUsers')
    op.drop_table('studentUsers')
    op.drop_table('staffUsers')
    op.drop_table('roles')
    # ### end Alembic commands ###
