"""empty message

Revision ID: 1dafe0f9b250
Revises: b3e30cac962e
Create Date: 2020-07-23 23:29:00.917832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dafe0f9b250'
down_revision = 'b3e30cac962e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('financing_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('months', sa.String(length=100), nullable=False),
    sa.Column('monthlyFee', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('job_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breathecodeID', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['breathecodeID'], ['profiles.breathecodeID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecodeID')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=200), nullable=False),
    sa.Column('bank', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('job_profiles')
    op.drop_table('invoices')
    op.drop_table('financing_agreements')
    op.drop_table('credit_notes')
    # ### end Alembic commands ###
