"""empty message

Revision ID: 39812126d85b
Revises: 
Create Date: 2020-08-15 15:37:58.107703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39812126d85b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('lastName', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('lastName', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teacher_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('lastName', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('lastName', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('cohort', sa.String(length=80), nullable=False),
    sa.Column('rut', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('student_questionnaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('questionnarie_details', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['staff_user'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_questionnaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('staff_user', sa.Integer(), nullable=False),
    sa.Column('questionnarie_details', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['staff_user'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('enrrollment_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breathecode_id'], ['profiles.breathecode_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id')
    )
    op.create_table('financing_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('monthlyFee', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rut', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('job_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['breathecode_id'], ['profiles.breathecode_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=200), nullable=False),
    sa.Column('bank', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('ruts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut_id', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['rut_id'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut_id')
    )
    op.create_table('student_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnarie_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questionnarie_id'], ['student_questionnaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnarie_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questionnarie_id'], ['teacher_questionnaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('teacher_user', sa.Integer(), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('questionnarie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breathecode_id'], ['profiles.breathecode_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['student_questions.id'], ),
    sa.ForeignKeyConstraint(['questionnarie_id'], ['student_questionnaries.id'], ),
    sa.ForeignKeyConstraint(['teacher_user'], ['teacher_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id'),
    sa.UniqueConstraint('question_id'),
    sa.UniqueConstraint('questionnarie_id'),
    sa.UniqueConstraint('teacher_user')
    )
    op.create_table('teacher_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('teacher_user', sa.Integer(), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('questionnarie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breathecode_id'], ['profiles.breathecode_id'], ),
    sa.ForeignKeyConstraint(['questionnarie_id'], ['teacher_questionnaries.id'], ),
    sa.ForeignKeyConstraint(['teacher_question_id'], ['teacher_questions.id'], ),
    sa.ForeignKeyConstraint(['teacher_user'], ['teacher_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id'),
    sa.UniqueConstraint('questionnarie_id'),
    sa.UniqueConstraint('teacher_question_id'),
    sa.UniqueConstraint('teacher_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_answers')
    op.drop_table('student_answers')
    op.drop_table('teacher_questions')
    op.drop_table('student_questions')
    op.drop_table('ruts')
    op.drop_table('payments')
    op.drop_table('job_profiles')
    op.drop_table('invoices')
    op.drop_table('financing_agreements')
    op.drop_table('enrrollment_agreements')
    op.drop_table('credit_notes')
    op.drop_table('teacher_questionnaries')
    op.drop_table('student_questionnaries')
    op.drop_table('profiles')
    op.drop_table('teacher_users')
    op.drop_table('student_users')
    op.drop_table('staff_users')
    op.drop_table('roles')
    # ### end Alembic commands ###
