"""empty message

Revision ID: 54dc8ffe9a2a
Revises: 3d6641c84b8e
Create Date: 2020-07-23 23:27:29.801630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dc8ffe9a2a'
down_revision = '3d6641c84b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('breathecodeID', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('cohort', sa.String(length=80), nullable=False),
    sa.Column('rut', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['studentUsers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecodeID'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
