"""empty message

Revision ID: b3e30cac962e
Revises: 54dc8ffe9a2a
Create Date: 2020-07-23 23:28:12.200253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e30cac962e'
down_revision = '54dc8ffe9a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrrollment_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('breathecodeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breathecodeID'], ['profiles.breathecodeID'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecodeID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrrollment_agreements')
    # ### end Alembic commands ###
