"""empty message

Revision ID: f3a88486691e
Revises: 
Create Date: 2021-11-08 18:21:21.110897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a88486691e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('enrrollment_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breathecode_id'], ['profiles.breathecode_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id')
    )
    op.create_table('financing_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('monthlyFee', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rut', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('job_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['breathecode_id'], ['profiles.breathecode_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.Column('payment_method', sa.String(length=200), nullable=False),
    sa.Column('bank', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rut'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('ruts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut_id', sa.Integer(), nullable=False),
    sa.Column('urlPDF', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['rut_id'], ['profiles.rut'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut_id')
    )
    op.create_table('student_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnarie_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questionnarie_id'], ['student_questionnaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnarie_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questionnarie_id'], ['teacher_questionnaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('teacher_user', sa.Integer(), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('questionnarie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breathecode_id'], ['profiles.breathecode_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['student_questions.id'], ),
    sa.ForeignKeyConstraint(['questionnarie_id'], ['student_questionnaries.id'], ),
    sa.ForeignKeyConstraint(['teacher_user'], ['teacher_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id'),
    sa.UniqueConstraint('question_id'),
    sa.UniqueConstraint('questionnarie_id'),
    sa.UniqueConstraint('teacher_user')
    )
    op.create_table('teacher_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('breathecode_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('questionnarie_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breathecode_id'], ['profiles.breathecode_id'], ),
    sa.ForeignKeyConstraint(['questionnarie_id'], ['teacher_questionnaries.id'], ),
    sa.ForeignKeyConstraint(['teacher_question_id'], ['teacher_questions.id'], ),
    sa.ForeignKeyConstraint(['teacher_user'], ['teacher_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breathecode_id', 'teacher_user', 'teacher_question_id', name='unique_teacher_answer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_answers')
    op.drop_table('student_answers')
    op.drop_table('teacher_questions')
    op.drop_table('student_questions')
    op.drop_table('ruts')
    op.drop_table('payments')
    op.drop_table('job_profiles')
    op.drop_table('invoices')
    op.drop_table('financing_agreements')
    op.drop_table('enrrollment_agreements')
    op.drop_table('credit_notes')
    # ### end Alembic commands ###
